// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgOYcdgXKp2y5GE_lqfclEGESXI8OROrc',
    appId: '1:898721431163:web:298b7ff604399c30d5acde',
    messagingSenderId: '898721431163',
    projectId: 'taskify-b756f',
    authDomain: 'taskify-b756f.firebaseapp.com',
    storageBucket: 'taskify-b756f.firebasestorage.app',
    measurementId: 'G-FDXXTMRJWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVeaX3cYBMfyfdte2QZcxKiuSCTcStgoM',
    appId: '1:898721431163:android:de1ff7755d15a11bd5acde',
    messagingSenderId: '898721431163',
    projectId: 'taskify-b756f',
    storageBucket: 'taskify-b756f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmHCLMoXPZqB93YYQaEgTJ_0T8wlCHgNs',
    appId: '1:898721431163:ios:4412d87322669dd1d5acde',
    messagingSenderId: '898721431163',
    projectId: 'taskify-b756f',
    storageBucket: 'taskify-b756f.firebasestorage.app',
    iosBundleId: 'com.example.taskify',
  );
}
